#ifndef BLINK_AVRLAUNCH_DEFS_H
#define BLINK_AVRLAUNCH_DEFS_H

#define EVENT_MAX_SOURCES 2
#define EVENT_MAX_LISTENERS 2
#define SCHEDULER_MAX_TASKS 5
#define SHELL_CMD_MAX_LENGTH 16
#define SHELL_MAX_HANDLERS 5

#endif
