#ifndef SYNTH_AVRLAUNCH_DEFS_H
#define SYNTH_AVRLAUNCH_DEFS_H

#define EVENT_MAX_SOURCES 5
#define EVENT_MAX_LISTENERS 5
#define SCHEDULER_MAX_TASKS 5
#define SHELL_CMD_MAX_LENGTH 16
#define SHELL_MAX_HANDLERS 6

#endif
