#ifndef AVRLAUNCH_DEFS_H
#define AVRLAUNCH_DEFS_H

#define EVENT_MAX_SOURCES 3
#define EVENT_MAX_LISTENERS 3
#define SCHEDULER_MAX_TASKS 2
#define SHELL_CMD_MAX_LENGTH 10
#define SHELL_MAX_HANDLERS 5

#endif
